
- name: Installing and configuring Docker 
  hosts: "docker"
  become: true
  #sudo: yes
  roles:
    - { role: docker, tags: ["docker"] }

- name: Setting up Logging Server
  hosts: "elk"
  become: true
  #sudo: yes                       
  roles:
    - {role: java, tags: ["java"]}
    - {role: nginx, tags: ["nginx"]} 
    - {role: ntp, tags: ["ntp"]}
    - { role: logging, tags: ["logging"] }


- name: Setting up Monitoring Server
  hosts: "zabbix"
  become: true
  #sudo: yes
  roles:
    - { role: monitoring, tags: ["monitoring"] }
    

- name: Setting up filebeat
  hosts: "general"
  become: true
  roles:
    - { role: filebeat, tags: ["filebeat"] }


- name: Setting up zabbix-client
  hosts: "general"
  become: true
  roles:
    - { role: zabbix, tags: ["filebeat"] }

- name: Setting up slack
  hosts: "slack"
  become: true
  roles:
    - { role: slack, tags: ["slack"] }
